
*SELECTION-SCREEN BEGIN OF SCREEN 050 AS WINDOW.
*
*SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME.
*PARAMETERS: p_versn TYPE t011-versn MEMORY ID bil OBLIGATORY,
*            p_bukrs TYPE bukrs      MEMORY ID buk OBLIGATORY,
*            p_gjahr TYPE gjahr      MEMORY ID gjr OBLIGATORY.
*
*SELECT-OPTIONS: s_saknr FOR ska1-saknr.
*SELECTION-SCREEN: BEGIN OF LINE.
*SELECTION-SCREEN COMMENT :  01(31) text-s02 FOR FIELD p_moini.
*PARAMETERS: p_moini TYPE monat      MEMORY ID ini OBLIGATORY.
*SELECTION-SCREEN COMMENT : 39(05) text-s03 FOR FIELD p_mofin.
*PARAMETERS: p_mofin TYPE monat      MEMORY ID fin OBLIGATORY.
*SELECTION-SCREEN END OF LINE.
*
*SELECTION-SCREEN END OF BLOCK b1.
*
*SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME.
*PARAMETERS: p_retif AS CHECKBOX USER-COMMAND rusr.
*SELECTION-SCREEN END OF BLOCK b2.
*
*SELECTION-SCREEN END OF SCREEN 050.






* Verificações de Entrada
AT SELECTION-SCREEN OUTPUT.


AT SELECTION-SCREEN.
  CASE sy-ucomm.
    WHEN 'CRET'.
      PERFORM limpa_objetos.
      PERFORM iniciar_classes.
    WHEN OTHERS.
  ENDCASE.
